// <auto-generated />
using System;
using DataBaseStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseStorage.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseStorage.entities.detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Khl")
                        .HasColumnType("float");

                    b.Property<double>("Vm")
                        .HasColumnType("float");

                    b.Property<double>("Ze")
                        .HasColumnType("float");

                    b.Property<double>("delta_h")
                        .HasColumnType("float");

                    b.Property<double>("dm1")
                        .HasColumnType("float");

                    b.Property<double>("sigmastr")
                        .HasColumnType("float");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("u")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("details");
                });

            modelBuilder.Entity("DataBaseStorage.entities.resultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("detailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sigmaH")
                        .HasColumnType("float");

                    b.Property<double>("sigmaHP")
                        .HasColumnType("float");

                    b.Property<Guid>("unitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("detailId");

                    b.HasIndex("unitId");

                    b.ToTable("resultEntities");
                });

            modelBuilder.Entity("DataBaseStorage.entities.unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ea")
                        .HasColumnType("float");

                    b.Property<double>("Ft")
                        .HasColumnType("float");

                    b.Property<double>("Kh")
                        .HasColumnType("float");

                    b.Property<double>("Kha")
                        .HasColumnType("float");

                    b.Property<double>("Khb")
                        .HasColumnType("float");

                    b.Property<double>("Khv")
                        .HasColumnType("float");

                    b.Property<double>("OmegaHT")
                        .HasColumnType("float");

                    b.Property<double>("OmegaHV")
                        .HasColumnType("float");

                    b.Property<double>("Re")
                        .HasColumnType("float");

                    b.Property<double>("Zh")
                        .HasColumnType("float");

                    b.Property<double>("Zm")
                        .HasColumnType("float");

                    b.Property<double>("b")
                        .HasColumnType("float");

                    b.Property<double>("def_sigmaH_sigmaHP")
                        .HasColumnType("float");

                    b.Property<double>("g0")
                        .HasColumnType("float");

                    b.Property<double>("sigmaH")
                        .HasColumnType("float");

                    b.Property<double>("sigmaHP")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("units");
                });

            modelBuilder.Entity("DataBaseStorage.entities.resultEntity", b =>
                {
                    b.HasOne("DataBaseStorage.entities.detail", "detail")
                        .WithMany()
                        .HasForeignKey("detailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseStorage.entities.unit", "unit")
                        .WithMany()
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("detail");

                    b.Navigation("unit");
                });
#pragma warning restore 612, 618
        }
    }
}
